

# Configuraci√≥n base de la aplicaci√≥n.

config_lateral_var: 
  encabezado: "Menu"

  list_formatos_cartas:
    - F Carta De Nivelacion Salarial - Salario Basico.docx
    - F Carta De Nivelacion Salarial - Salario Integral.docx
    - F Carta de Nivelaci√≥n Salarial - Salario Variable.docx
    - F Cartas de Nombramiento Salario Variable.docx
    - F Carta de Nombramiento - Salario Basico (Sin cambio de salario).docx
    - F Otros√≠ cambio de contrato.docx
    - F Otro Si Licencia No Remunerada por Estudio.docx
    - F Otrosi de Traslados con Bonificaci√≥n.docx
    - F Otrosi de Traslados Sin Bonificaci√≥n.docx
    - F Otrosi de cambio Salario Variable a Fijo.docx
  
  formatos_sin_digitaci√≥n:
    - F Otros√≠ cambio de contrato.docx

  config_formatos:
    "F Carta De Nivelacion Salarial - Salario Basico.docx":
      campos_digitar: 
        "Fecha_dia_actual" : "Ingrese la fecha de realizaci√≥n de la carta: (DD de MM de AAAA)"
        "DD de MM de AA" : 'Fecha inicio nuevo cargo. (DD de MM de AAAA):'
        "$ Salario" : 'Nuevo salario del colaborador (Ejm: $2.500.000)'
      campos_buscar:
        "Nombre Completo del Empleado" : "NOMBRE COMPLETO EMPLEADO"
        "Nombre empleado": "NOMBRE EMPLEADO"
        "Ciudad" : "CIUDAD DE TRABAJO"
      contiene_tablas: "No"
    "F Carta de Nivelaci√≥n Salarial - Salario Variable.docx":
      campos_digitar: 
        "Fecha_dia_actual" : "Fecha de realizaci√≥n de la carta: (DD de MM de AAAA)"
        "DD de MM de AA" : 'Fecha inicio nuevo cargo. (DD de MM de AAAA):'
        "Salario B√°sico." : 'Salario base del colaborador: (Ejm: 1.000.000)'
        "Salario Variable." : "Salario variable del colaborador: (Ejm: 500.000) "
      campos_buscar:
        "Nombre Completo del Empleado" : "NOMBRE COMPLETO EMPLEADO"
        "Nombre empleado": "NOMBRE EMPLEADO"
        "Ciudad" : "CIUDAD DE TRABAJO"
      contiene_tablas: "S√≠"
    "F Carta de Nombramiento - Salario Basico (Sin cambio de salario).docx":
      campos_digitar: 
        "Fecha_dia_actual" : "Fecha de realizaci√≥n de la carta: (DD de MM de AAAA)"
        "DD de MM de AA" : 'Fecha inicio nuevo cargo. (DD de MM de AAAA):'
        "Nuevo Cargo" : 'Nuevo cargo del colaborador: '
      campos_buscar:
        "Nombre Completo del Empleado" : "NOMBRE COMPLETO EMPLEADO"
        "Nombre empleado": "NOMBRE EMPLEADO"
        "Ciudad" : "CIUDAD DE TRABAJO"
      contiene_tablas: "No"
    "F Carta De Nivelacion Salarial - Salario Integral.docx":
      campos_digitar: 
        "Fecha_dia_actual" : "Fecha de realizaci√≥n de la carta: (DD de MM de AAAA)"
        "DD de MM de AA" : 'Fecha inicio nuevo salario. (DD de MM de AAAA):'
        "Nombre del cargo": "Cargo del empleado."
        "$ Salario" : 'Nuevo salario del colaborador (Ejm: 2.500.000)'
        "Num_horas_semanales" : "Horas semanales de trabajo (Ejm: 45 Of entrar / 47 Region)"
      campos_buscar:
        "Nombre Completo del Empleado" : "NOMBRE COMPLETO EMPLEADO"
        "Nombre empleado": "NOMBRE EMPLEADO"
        "Ciudad" : "CIUDAD DE TRABAJO"
      contiene_tablas: "No"
    "F Cartas de Nombramiento Salario Variable.docx":
      campos_digitar: 
        "Fecha_dia_actual" : "Fecha de realizaci√≥n de la carta: (DD de MM de AAAA)"
        "DD de MM de AA" : 'Fecha inicio nuevo salario. (DD de MM de AAAA):'
        "Nuevo Cargo" : 'Nuevo cargo del colaborador: '
        "Salario B√°sico." : 'Salario base del colaborador: (Ejm: $ 1.000.000)'
        "Salario Variable." : "Salario variable del colaborador: (Ejm: $ 500.000) "
      campos_buscar:
        "Nombre Completo del Empleado" : "NOMBRE COMPLETO EMPLEADO"
        "Nombre empleado": "NOMBRE EMPLEADO"
        "Ciudad" : "CIUDAD DE TRABAJO"
      contiene_tablas: "S√≠"
    "F Formalizaci√≥n de APL en Cargo.docx":
      campos_digitar: 
        "Fecha_dia_actual" : "Fecha de realizaci√≥n de la carta: (DD de MM de AAAA)"
        "DD de MM de AA" : 'Fecha inicio nuevo salario. (DD de MM de AAAA):'
        "Nuevo Cargo" : 'Nuevo cargo del colaborador: '
        "$ Salario" : 'Salario B√°sico mensual (Ejm: 2.500.000)'
      campos_buscar:
        "Nombre Completo del Empleado" : "NOMBRE COMPLETO EMPLEADO"
        "Nombre empleado": "NOMBRE EMPLEADO"
        "Ciudad" : "CIUDAD DE TRABAJO"
        "Documento de identidad l√≠der" : "CEDULA_LIDER"
        "Documento de identidad" : CEDULA
        "Fecha_antiguedad": "FECHA_ANTIGUEDAD_FORMATEADA"
      contiene_tablas: "No"
    "F Otro Si Licencia No Remunerada por Estudio.docx":
      campos_digitar: 
        "Fecha de inicio licencia": "Fecha de inicio de la licencia: (DD de Mes de AAAA)"
        "Fecha Final de Licencia" : "Fecha de fin de la licencia: (DD de Mes de AAAA)" 
      campos_buscar:
        "Nombre Completo del Empleado" : "NOMBRE COMPLETO EMPLEADO"
        "Nombre empleado": "NOMBRE EMPLEADO"
        "Documento de identidad" : CEDULA
      contiene_tablas: "No"
    "F Otros√≠ cambio de contrato.docx":
      campos_buscar:
        "Nombre Completo del Empleado" : "NOMBRE COMPLETO EMPLEADO"
        "Nombre empleado": "NOMBRE EMPLEADO"
        "Documento de identidad" : CEDULA
        "Fecha_antiguedad": FECHA_ANTIGUEDAD_FORMATEADA
        "Cargo actual del empleado" : "CARGO"
      contiene_tablas: "No"
    "F Otrosi de Traslados con Bonificaci√≥n.docx":
      campos_digitar:
        "LUGAR DE DESTINO" : "Nuevo lugar de trabajo del empleado (Ciudad)"
        "DD de MM de AA" : 'Fecha inicio nueva sede laboral. (DD de MM de AAAA):'
        "$ Salario " : "Ingrese la bonificaci√≥n por traslado (Ejm: $ 200.000)"
      campos_buscar:
        "Nombre Completo del Empleado" : "NOMBRE COMPLETO EMPLEADO"
        "Nombre empleado": "NOMBRE EMPLEADO"
        "LUGAR DE ORIGEN" : "CIUDAD DE TRABAJO"
        "Documento de identidad" : CEDULA
        "Fecha_antiguedad": FECHA_ANTIGUEDAD_FORMATEADA
        "Cargo actual del empleado" : "CARGO"
      contiene_tablas: "No"
    "F Otrosi de Traslados Sin Bonificaci√≥n.docx":
      campos_digitar:
        "LUGAR DE DESTINO" : "Nuevo lugar de trabajo del empleado (Ciudad)"
        "DD de MM de AA" : 'Fecha inicio nueva sede laboral. (DD de MM de AAAA):'
        "$ Salario " : "Ingrese la bonificaci√≥n por traslado (Ejm: $ 200.000)"
      campos_buscar:
        "Nombre Completo del Empleado" : "NOMBRE COMPLETO EMPLEADO"
        "Nombre empleado": "NOMBRE EMPLEADO"
        "LUGAR DE ORIGEN" : "CIUDAD DE TRABAJO"
        "Documento de identidad" : CEDULA
        "Fecha_antiguedad": FECHA_ANTIGUEDAD_FORMATEADA
        "Cargo actual del empleado" : "CARGO"
      contiene_tablas: "No"
    "F Otrosi de cambio Salario Variable a Fijo.docx":
      campos_digitar:
        "LUGAR DE DESTINO" : "Nuevo lugar de trabajo del empleado (Ciudad)"
        "DD de MM de AA" : 'Fecha inicio nueva sede laboral. (DD de MM de AAAA):'
        "$ Salario " : "Ingrese la bonificaci√≥n por traslado (Ejm: $ 200.000)"
      campos_buscar:
        "Nombre Completo del Empleado" : "NOMBRE COMPLETO EMPLEADO"
        "Nombre empleado": "NOMBRE EMPLEADO"
        "LUGAR DE ORIGEN" : "CIUDAD DE TRABAJO"
        "Documento de identidad" : CEDULA
        "Fecha_antiguedad": FECHA_ANTIGUEDAD_FORMATEADA
        "Cargo actual del empleado" : "CARGO"
      contiene_tablas: "No"


  seccion_archivo:
    file_uploader_maestra:
      clave: "archivo_maestra"
      titulo: "Cargar maestra de personal"
      uploader_msg: "üì§ Adjuntar maestra personal"
      limit_msg: "Tama√±o m√°ximo 200MB"
      button_msg: "üóÇÔ∏è Examinar"
      tipo_archivos: [".xlsx"]
      icon: "MdUploadFile"

  seccion_buscar_colab:
    btn_agregar_colab:
      clave : btn_agregar_colab
      etiqueta : Agregar colaborador

    select_box_colaborador:
      clave: "selector_colaboradores"
      etiqueta : "Seleccione un colaborador"


cnf_session_keys:
  editor_df_key: "editor_df_final"
  inicializacion:
    indice_campo:
      valor_inicial : 0
    text_input_cedulas:
      valor_inicial: "sin_cedula"
    campos_guardados:
      valor_inicial: {}
    colaborador_habilitado: 
      valor_inicial: False
    proceso_documento_habilitado:
      valor_inicial:  False
    nueva_incidencia:
      valor_inicial: False

  claves_preservar: 
    - formatos_cartas
    - maestra_personal
    - archivo_maestra_mensaje_mostrado"


Resultados:
  path_resultado: "Resultados\\"

dict_cols: 
  "Sociedad": "Sociedad"
  "Cta.alternativa": "Cta.alternativa"
  "N¬∫ cuenta": "N¬∫ cuenta"
  "Texto p.posici√≥n balance/PyG": "Texto p.posici√≥n balance/PyG"
  "TotPerInf": "TotPerInf"
  "TotPerComp": "TotPerComp"
  "Desv.abs.": "Desv.abs."
  "Mon.": "Mon."
  "agrupador_base" : "agrupador_base"
  "x" : "x"
  "y" : "y"
  "descripcion_cuenta" : "descripcion_cuenta"
